name: Build and deploy ASP app to Azure Web App - gitHubDeployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted  # Self-hosted runner

    steps:
      - uses: actions/checkout@v4  # Checkout the code

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v2

      # - name: Setup NuGet
      #   uses: NuGet/setup-nuget@v1.0.5

    

     
      - name: Build
        shell: cmd
        run: |
          msbuild GithubProject.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"

    
      - name: Upload artifact
        uses: actions/upload-artifact@v4  #  Updated version
        with:
          name: build-artifact
          path: "./_build"
 
  download-artifact:
    runs-on: Runner
    needs: build  # This ensures it runs only after the 'build' job completes successfully
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4  # Latest version
        with:
          name: build-artifact
          path: D:\MyWork\Github_Actions\Runner\Artifact\.NEt_Framework_Artifact

      # - name: Set up Azure CLI
      #   uses: azure/azure-cli-action@v1
     # Step 7: Login to Azure using the service principal
      - name: Azure Login
        uses: azure/login@v1
        with:
         # client-id: ${{ secrets.AZURE_CLIENT_ID }}
         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
         client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
   # Step 8: Deploy ARM template to create the Web App
      - name: Deploy ARM template to create Azure Web App
        run: |
         az deployment sub create \
           --name createWebAppDeployment \
           --location eastus \
           --template-file ./azure-webapp-template.json \
           --parameters webAppName=<githubsebanaHai> appServicePlanName=<GitHubSeAyaHoon>
  
  
          
        
    


  # approve:
  #   runs-on: self-hosted
  #   needs: build
  #   environment:
  #     name: approveit 
  #   steps:
  #     - name: Wait for approval before deploying to production
  #       run: echo "Waiting for manual approval to deploy to production"






          
  deploy:
    runs-on: self-hosted 
    needs: build
    environment:
      name: 'Production'
      url: "githubactiondeployment-apewgvf8d9hxhhfu.northeurope-01.azurewebsites.net"

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'githubActionDeployment'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_168A2A56EB3A467789F36DB82C94484F }}
          package:  D:\MyWork\Github_Actions\Runner\Artifact\.NEt_Framework_Artifact
# =-----------------------------------------------

 
  
