name: Build and deploy ASP app to Azure Web App - gitHubDeployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted  # Ensure this runner has .NET Framework and SonarScanner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Optional: Setup NuGet if you're restoring packages
      # - name: Setup NuGet
      #   uses: NuGet/setup-nuget@v1.0.5

      - name: Begin SonarQube Analysis
        shell: cmd
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          "C:\sonar-scanner-msbuild\SonarScanner.MSBuild.exe" begin ^
            /k:"TrainingDemo_UI:master" ^
            /n:"githubAction" ^
            /d:sonar.host.url="https://sonar.cybage.com" ^
            /d:sonar.login=%SONAR_TOKEN% ^
            /d:sonar.verbose=true

      - name: Build Project
        shell: cmd
        run: |
          msbuild GithubProject.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish ^
            /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" ^
            /p:configuration="Release" /p:PublishUrl="../_build"

      - name: End SonarQube Analysis
        shell: cmd
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          "C:\sonar-scanner-msbuild\SonarScanner.MSBuild.exe" end ^
            /d:sonar.login=%SONAR_TOKEN%

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: "./_build"
